parameters:
#    conference.example.class: my\conferenceBundle\Example

services:
#    conference.example:
#        class: %conference.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
